[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "postgresql",       # for pg_config required by psycopg2
  "freetype",
  "pkg-config",
  "libjpeg",
  "zlib"
]

[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]
